### ISSUE TITLE
invariant check pass

### ISSUE THREAD

**Issue by andrewchambers** [rui314/9cc#10]
Some node types and c types have a few invariants assumed, perhaps there could be an optional check pass in between stages that basically just documents + checks. I remember 8cc had one about the left and right side of a '+' if there was a pointer type for example.

I can see an argument against it in terms of keeping the codebase small. Its just more annoying to remember every assumption and add it later.

As always, I don't mind what approach you take, just a point for discussion.

**Comment by rui314** [comment]
Rejecting bad expressions such as ptr+ptr is sema's task. It is just incomplete. I will eventually extend it so that it can find all bad expressions.
