### ISSUE TITLE
Support for out-of-source builds

### ISSUE THREAD

**Issue by elfring** [rui314/9cc#4]
How do you think about to benefit from [parallel build trees](https://www.gnu.org/software/automake/manual/html_node/VPATH-Builds.html "Parallel build trees (a.k.a. VPATH builds)") also for this software?
Would you like to [support out-of-source](https://gitlab.kitware.com/cmake/community/wikis/FAQ#what-is-an-out-of-source-build "https://gitlab.kitware.com/cmake/community/wikis/FAQ#what-is-an-out-of-source-build") ([VPATH](https://www.gnu.org/software/make/manual/html_node/General-Search.html "Search path for all prerequisites")) builds?

**Comment by rui314** [comment]
That might be a good thing to do, but since 9cc is not a usable program yet, I don't think we should do that at the moment. I'd keep it as simple as possible at this stage, so people can understand everything easily.
